FROM node:20-bullseye-slim

ARG NEXT_PUBLIC_API_URL=http://backend:4000
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY app ./app
COPY components ./components
COPY public ./public
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
