apiVersion: v1
kind: Service
metadata:
  name: interview-frontend
spec:
  type: NodePort
  selector:
    app: interview-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
